# Generated by Django 4.1.2 on 2022-12-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
