# Generated by Django 4.1.2 on 2022-12-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_post_likes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
